manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Divoolej
      url-base: https://github.com/Divoolej
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-behavior-divled
      remote: Divoolej
      revision: main
      import: west.yml
  self:
    path: config
